// Auto-generated from 酒馆助手脚本-像素拓麻歌子v0.44.3.json
// This preserves the embedded pixel-art rows as data; Unity renders them at runtime.
using System;
namespace PixelTamagotchi {
[Serializable] public class ColorVariant { public string SpeciesId; public string Id; public string Name; public string Primary; public string Secondary; public string Accent; }
[Serializable] public class PetSpecies { public string Id; public string Name; public string Trait; public int LifespanDays; public string[][] Frames; public string[][] AdultFrames; }
public static class GeneratedPetDatabase {
public static readonly ColorVariant[] ColorVariants = new ColorVariant[] {
  new ColorVariant { SpeciesId="leaf_blob", Id="mint", Name="薄荷绿", Primary="#73c2a3", Secondary="#a9e3c9", Accent="#ef8f9d" },
  new ColorVariant { SpeciesId="leaf_blob", Id="rose", Name="莓果粉", Primary="#e892ad", Secondary="#f4bfd0", Accent="#8fbf73" },
  new ColorVariant { SpeciesId="leaf_blob", Id="honey", Name="蜂蜜黄", Primary="#e5b957", Secondary="#f5d98b", Accent="#7da66f" },
  new ColorVariant { SpeciesId="moon_cat", Id="silver", Name="月银", Primary="#aebcc9", Secondary="#dbe4ea", Accent="#6c7fa8" },
  new ColorVariant { SpeciesId="moon_cat", Id="night", Name="夜蓝", Primary="#526789", Secondary="#8294b3", Accent="#e8c86c" },
  new ColorVariant { SpeciesId="moon_cat", Id="cream", Name="奶油", Primary="#e9d5ad", Secondary="#fff0d0", Accent="#bc7f86" },
  new ColorVariant { SpeciesId="cloud_bunny", Id="snow", Name="云雪白", Primary="#e8eee9", Secondary="#ffffff", Accent="#e8a0af" },
  new ColorVariant { SpeciesId="cloud_bunny", Id="lilac", Name="丁香紫", Primary="#b8a7d7", Secondary="#d9caef", Accent="#f1a3b4" },
  new ColorVariant { SpeciesId="cloud_bunny", Id="peach", Name="蜜桃橙", Primary="#e9ad8e", Secondary="#f6cfb9", Accent="#c87882" },
  new ColorVariant { SpeciesId="star_chick", Id="sun", Name="太阳黄", Primary="#e6bd51", Secondary="#f5db87", Accent="#e17d54" },
  new ColorVariant { SpeciesId="star_chick", Id="sky", Name="晴空蓝", Primary="#78b8d1", Secondary="#a9daea", Accent="#ef9c58" },
  new ColorVariant { SpeciesId="star_chick", Id="berry", Name="星莓粉", Primary="#dc8ca8", Secondary="#f0b9ca", Accent="#efb055" },
  new ColorVariant { SpeciesId="ember_fox", Id="amber", Name="琥珀橙", Primary="#df884d", Secondary="#f1ba7e", Accent="#fff0cf" },
  new ColorVariant { SpeciesId="ember_fox", Id="snow", Name="雪原白", Primary="#dce3e5", Secondary="#ffffff", Accent="#8da8bc" },
  new ColorVariant { SpeciesId="ember_fox", Id="dusk", Name="暮霞紫", Primary="#8f6c9c", Secondary="#baa0c4", Accent="#f1b46a" },
  new ColorVariant { SpeciesId="aqua_axolotl", Id="coral", Name="珊瑚粉", Primary="#e493a2", Secondary="#f2bdc6", Accent="#c96d8f" },
  new ColorVariant { SpeciesId="aqua_axolotl", Id="aqua", Name="水蓝", Primary="#74bdc2", Secondary="#a7dde0", Accent="#5d8dac" },
  new ColorVariant { SpeciesId="aqua_axolotl", Id="violet", Name="雨藤紫", Primary="#9d8bc2", Secondary="#c7b8e0", Accent="#e69aaf" },
};
public static readonly PetSpecies[] Species = new PetSpecies[] {
  new PetSpecies { Id="leaf_blob", Name="叶团", Trait="头顶新芽、没有明显脖颈的圆滚滚软团。", LifespanDays=32, Frames=new string[][] { new string[] { "......KK........", ".....KAAK.......", "....KABAK.......", ".....KAK........", "...KKAAAKK......", "..KAAAAAAAAK....", ".KAAABBBBAAAK...", ".KAAWAAAAWAAK...", ".KAAAAAAAAAAK...", ".KAAAAPAAAAAK...", "..KAAAAAAAAK....", "...KAAAAAAK.....", "....KKAAKK......", "...KK....KK.....", "................", "................" }, new string[] { "......KK........", ".....KAAK.......", "....KABAK.......", ".....KAK........", "...KKAAAKK......", "..KAAAAAAAAK....", ".KAAABBBBAAAK...", ".KAAKAAAAKAAK...", ".KAAAAAAAAAAK...", ".KAAAAPAAAAAK...", "..KAAAAAAAAK....", "...KAAAAAAK.....", "....KKAAKK......", "..KK......KK....", "................", "................" } }, AdultFrames=new string[][] { new string[] { "....KBBK.KBBK...", "...KBBBBKBBBBK..", "..KBBBBBBBBBBK..", "...KKKAAAAKKK...", "..KAAAAAAAAAAK..", ".KAAWAAAAAAWAAK.", ".KAAAAAPAAAAAAK.", "KAAAAAAAAAAAAAAK", "KAAAAAAAAAAAAAAK", ".KAAAAAAAAAAAAK.", "..KAAAAAAAAAAK..", "...KAAAAAAK.....", "..KAAK..KAAK....", ".KKK......KKK...", "................", "................" }, new string[] { "....KBBK.KBBK...", "...KBBBBKBBBBK..", "..KBBBBBBBBBBK..", "...KKKAAAAKKK...", "..KAAAAAAAAAAK..", ".KAAKAAAAAAKAAK.", ".KAAAAAPAAAAAAK.", "KAAAAAAAAAAAAAAK", "KAAAAAAAAAAAAAAK", ".KAAAAAAAAAAAAK.", "..KAAAAAAAAAAK..", "..KAAAAAAAAAAK..", ".KAAK......KAAK.", "KKK..........KKK", "................", "................" } } },
  new PetSpecies { Id="moon_cat", Name="月猫", Trait="成年后呈端坐猫科姿态，双耳高耸、额头月纹清晰，长尾会绕到身体一侧形成环形轮廓。", LifespanDays=36, Frames=new string[][] { new string[] { "..KK........KK..", ".KAAK......KAAK.", "KAAAAK....KAAAAK", "KAAAKKKKKKKAAAK.", "KAAAAAAAAAAAAAAK", "KAAWAAAAAAWAAAAK", "KAAAAPPPAAAAAAAK", "KAAAAAPAAAAAAAAK", ".KAAAAAAAAAAAAK.", "..KAAAAAAAAAAK..", "...KAAAAAAAAK...", "...KAAK..KAAK...", "..KK........KK..", "...........KAAK.", ".........KKAAK..", "..........KKK..." }, new string[] { "..KK........KK..", ".KAAK......KAAK.", "KAAAAK....KAAAAK", "KAAAKKKKKKKAAAK.", "KAAAAAAAAAAAAAAK", "KAAKAAAAAAKAAAAK", "KAAAAPPPAAAAAAAK", "KAAAAAPAAAAAAAAK", ".KAAAAAAAAAAAAK.", "..KAAAAAAAAAAK..", "...KAAAAAAAAK...", "...KAAK..KAAK...", "..KK........KK..", "..........KAAK..", "........KKAAK...", ".........KKK...." } }, AdultFrames=new string[][] { new string[] { "..KK........KK..", ".KAAK......KAAK.", "KABAK......KABAK", "KAAAKKKKKKKAAAK.", ".KAAAAPPPAAAAAK.", ".KAAWAAAAAAWAAK.", ".KAAAAAPAAAAAAK.", "..KAAAAAAAAAAK..", "...KAAAAAAAAK...", "...KAAAAAAAAK...", "..KAAK....KAAK..", ".KAAK......KAAK.", ".KKK......KAAAK.", ".........KAAAAK.", ".......KAAAAAK..", "........KKKK...." }, new string[] { "..KK........KK..", ".KAAK......KAAK.", "KABAK......KABAK", "KAAAKKKKKKKAAAK.", ".KAAAAPPPAAAAAK.", ".KAAKAAAAAAKAAK.", ".KAAAAAPAAAAAAK.", "..KAAAAAAAAAAK..", "...KAAAAAAAAK...", "..KAAAAAAAAAAK..", ".KAAK......KAAK.", "KAAK........KAAK", ".KKK.......KAAAK", ".........KAAAAK.", "........KAAAAK..", ".........KKK...." } } },
  new PetSpecies { Id="cloud_bunny", Name="云兔", Trait="超长耳朵和云朵般蓬松的宽大身体。", LifespanDays=34, Frames=new string[][] { new string[] { "....KK....KK....", "...KAAK..KAAK...", "...KAAK..KAAK...", "...KBAK..KABK...", "...KAAK..KAAK...", "....KAKKKKAK....", "...KAAAAAAAAK...", "..KAAWAAAAWAAK..", ".KAAAAAAAAAAAAK.", "KAAAABBBBBAAAAAK", "KAAAAAAAAAAAAAAK", ".KAAAAAAAAAAAAK.", "..KKAAAAAAAAKK..", ".KK..KK..KK..KK.", "................", "................" }, new string[] { "....KK....KK....", "...KAAK..KAAK...", "...KAAK..KAAK...", "...KBAK..KABK...", "...KAAK..KAAK...", "....KAKKKKAK....", "...KAAAAAAAAK...", "..KAAKAAAAKAAK..", ".KAAAAAAAAAAAAK.", "KAAAABBBBBAAAAAK", "KAAAAAAAAAAAAAAK", ".KAAAAAAAAAAAAK.", ".KKKAAAAAAAAKKK.", "................", "................", "................" } }, AdultFrames=new string[][] { new string[] { "...KK......KK...", "..KAAK....KAAK..", "..KAAK....KAAK..", "..KABK....KBAK..", "..KAAK....KAAK..", "..KAAK....KAAK..", "...KAKKKKKKAK...", "..KAAWAAAAWAAK..", "..KAAAAAAAAAAK..", "...KAAAPAAAK....", "..KAAAAAAAAAAK..", ".KAAAAAAAAAAAAK.", "KAAAABBBBBBAAAAK", ".KAAAK....KAAAK.", "KKKK........KKKK", "................" }, new string[] { "...KK......KK...", "..KAAK....KAAK..", "..KAAK....KAAK..", "..KABK....KBAK..", "..KAAK....KAAK..", "..KAAK....KAAK..", "...KAKKKKKKAK...", "..KAAKAAAAKAAK..", "..KAAAAAAAAAAK..", "...KAAAPAAAK....", "..KAAAAAAAAAAK..", ".KAAAAAAAAAAAAK.", "KAAAABBBBBBAAAAK", "KAAAK......KAAAK", ".KKK........KKK.", "................" } } },
  new PetSpecies { Id="star_chick", Name="星雏", Trait="星形冠羽、小翅膀和细细双脚的圆鸟。", LifespanDays=28, Frames=new string[][] { new string[] { ".......K........", "......KPK.......", ".....KPPPK......", "....KKAAAKK.....", "...KAAAAAAAK....", "..KAAWAAWAAAK...", ".KBAAAAAPAAAABK.", "KBBBAAAAAAAABBBK", ".KBAAAAAAAAAABK.", "..KAAAAAAAAAAK..", "...KAAAAAAAAK...", "....KAAAAAAK....", "...KKK....KKK...", "....K......K....", "................", "................" }, new string[] { ".......K........", "......KPK.......", ".....KPPPK......", "....KKAAAKK.....", "...KAAAAAAAK....", "..KAAKAAKAAAK...", ".KBAAAAAPAAAABK.", "KBBBAAAAAAAABBBK", ".KBAAAAAAAAAABK.", "..KAAAAAAAAAAK..", "...KAAAAAAAAK...", "....KAAAAAAK....", "..KKK......KKK..", "................", "................", "................" } }, AdultFrames=new string[][] { new string[] { "......KPK.......", "....KKPPPKK.....", "...KPPPPPPPK....", "..KKAAAAAAAKK...", "..KAAWAAAWAAK...", ".KAAAAPAAAAAAK..", "KBBBBAAAAAABBBBK", "KBBBBKAAAAKBBBBK", ".KBBBKAAAAKBBBK.", "..BBBKAAAAKBBB..", "...KAAAAAAAAK...", "....KAAAAAAK....", ".....KAAAAK.....", "....KK....KK....", "...KAK....KAK...", "..KKK......KKK.." }, new string[] { "......KPK.......", "....KKPPPKK.....", "...KPPPPPPPK....", "..KKAAAAAAAKK...", "..KAAKAAAKAAK...", ".KAAAAPAAAAAAK..", ".KBBBAAAAAABBBK.", "KBBBBKAAAAKBBBBK", "KBBBBAAAAAABBBBK", ".KBBBKAAAAKBBBK.", "...KAAAAAAAAK...", "....KAAAAAAK....", ".....KAAAAK.....", "...KK......KK...", "..KAK......KAK..", ".KKK........KKK." } } },
  new PetSpecies { Id="ember_fox", Name="焰狐", Trait="成年后转为侧身四足狐形，长吻、尖耳、修长躯干与占据后半画面的巨型火焰尾最醒目。", LifespanDays=35, Frames=new string[][] { new string[] { "..KK........KK..", ".KAAK......KAAK.", "KAAAAK....KAAAAK", "KABAAKKKKKKABAAK", "KAAAAAAAAAAAAAAK", "KAAWAAAAAAWAAAAK", "KAAAAAPPPAAAAAAK", ".KAAAAAAAAAAAAK.", "..KAAAAAAAAAAK..", "...KAAAAAAAAK...", "...KAAK..KAAK...", "..KK......KK....", ".........KBBBK..", ".......KKBBBBAK.", ".....KKBBBBBAAK.", "....KBBBBBAAKK.." }, new string[] { "..KK........KK..", ".KAAK......KAAK.", "KAAAAK....KAAAAK", "KABAAKKKKKKABAAK", "KAAAAAAAAAAAAAAK", "KAAKAAAAAAKAAAAK", "KAAAAAPPPAAAAAAK", ".KAAAAAAAAAAAAK.", "..KAAAAAAAAAAK..", "...KAAAAAAAAK...", "...KAAK..KAAK...", "..KK......KK....", "........KBBBK...", "......KKBBBBAK..", "....KKBBBBBAAK..", "...KBBBBBAAKK..." } }, AdultFrames=new string[][] { new string[] { "....K...........", "...KAK..........", "..KABK..........", ".KAAAKKKK.......", "KAAWAAAAAKK.....", ".KAAAAAAAAAKK...", "..KAAAAAAAAAAK..", "...KAAAAAAAABBK.", "..KAAKAAAAKBBBK.", ".KAAK....KBBBBK.", ".KKK.....KBBBBK.", "..K......KBBBPK.", ".KKK......KBBPK.", "..........KBBBK.", "...........KKK..", "................" }, new string[] { "....K...........", "...KAK..........", "..KABK..........", ".KAAAKKKK.......", "KAAKAAAAAKK.....", ".KAAAAAAAAAKK...", "..KAAAAAAAAAAK..", "...KAAAAAAABBBK.", "...KAAKAAKBBBBK.", "..KAAK...KBBBBK.", ".KKK.....KBBBPK.", "..K.......KBBPK.", ".KKK......KBBBK.", "..........KBBK..", "...........KK...", "................" } } },
  new PetSpecies { Id="aqua_axolotl", Name="水团蝾", Trait="幼年期为大头短肢的水生幼体，尾鳍明显；成年后形成对称外鳃冠与向下回卷的宽大游鳍尾。", LifespanDays=40, Frames=new string[][] { new string[] { "PP............PP", "PKP..........PKP", ".PKKKKKKKKKKKKP.", ".KAAAAAAAAAAAAK.", "KAAWAAAAAAAAWAAK", "KAAAAPPPAAAAAAAK", ".KAAAAAAAAAAAAK.", "..KKAAAAAAAAKK..", "....KAAAAAAK....", "...KAAK..KAAK...", "...KK......KK...", ".........KBBK...", ".......KKBBBK...", ".....KKBBBBBK...", "....KBBBBAAK....", ".....KKKKK......" }, new string[] { ".PP..........PP.", "PKP..........PKP", ".PKKKKKKKKKKKKP.", ".KAAAAAAAAAAAAK.", "KAAKAAAAAAAAKAAK", "KAAAAPPPAAAAAAAK", ".KAAAAAAAAAAAAK.", "..KKAAAAAAAAKK..", "....KAAAAAAK....", "...KAAK..KAAK...", "...KK......KK...", "........KBBK....", "......KKBBBK....", "....KKBBBBBK....", "...KBBBBAAK.....", "....KKKKK......." } }, AdultFrames=new string[][] { new string[] { "P.P..........P.P", "PPPK........KPPP", "PAAKKKKKKKKKAAAP", ".KAAAAAAAAAAAAK.", "KAAWAAAAAAAAWAAK", "KAAAAPPPAAAAAAAK", ".KAAAAAAAAAAAAK.", "..KKAAAAAAAAKK..", "...KAAAAAAAABK..", "..KAAK....KBBBK.", ".KK.......KBBBBK", ".........KBBBBBK", ".......KBBBBBBBK", ".....KBBBBBBBBAK", "...KBBBBBBAAAAK.", "....KKKKKKKKK..." }, new string[] { ".P.P........P.P.", "PPPK........KPPP", "PAAKKKKKKKKKAAAP", ".KAAAAAAAAAAAAK.", "KAAKAAAAAAAAKAAK", "KAAAAPPPAAAAAAAK", ".KAAAAAAAAAAAAK.", "..KKAAAAAAAAKK..", "..KBAAAAAAAAABK.", ".KBBBK....KAAK..", "KBBBBK.......KK.", "KBBBBBK.........", "KBBBBBBBK.......", "KABBBBBBBBK.....", ".KAAAABBBBBBK...", "...KKKKKKKKK...." } } },
};
public static PetSpecies FindSpecies(string id) { foreach (var s in Species) if (s.Id == id) return s; return Species.Length > 0 ? Species[0] : null; }
public static ColorVariant[] FindColors(string speciesId) { var list = new System.Collections.Generic.List<ColorVariant>(); foreach (var c in ColorVariants) if (c.SpeciesId == speciesId) list.Add(c); return list.ToArray(); }
public static ColorVariant FindColor(string speciesId, string colorId) { foreach (var c in ColorVariants) if (c.SpeciesId == speciesId && c.Id == colorId) return c; var arr = FindColors(speciesId); return arr.Length > 0 ? arr[0] : null; }
}
}